### ISSUE TITLE
Advice or plugin recommendation

### ISSUE THREAD

**Issue by Razgort** [iwnow/angular-plugin-example#1]
Hello guys,
I'm very interesting in your project.
In fact i'm building for my company a large application.
This app is based on asp core and angular 7.
But we want this app to be extensible on the backend part AND on the front (angular) part.
Because we will publish this app compiled and give it to our integrators that will want to do their own specific development around our app. I'm not sure if i'm understandable.
Ask me if not.

But anyway in our study case would you recommand we use your framework  for the front end part ?
We are looking for the Extcore extension for the backend part, are you compatible with it ?
Also we will migrate to asp core 3.0 once it will be in release. Do you have plans for supporting it ?

Thanks in advance,
Alexandre MOULAY

**Comment by iwnow** [comment]
> Hello guys,
> I'm very interesting in your project.
> In fact i'm building for my company a large application.
> This app is based on asp core and angular 7.
> But we want this app to be extensible on the backend part AND on the front (angular) part.
> Because we will publish this app compiled and give it to our integrators that will want to do their own specific development around our app. I'm not sure if i'm understandable.
> Ask me if not.
> 
> But anyway in our study case would you recommand we use your framework for the front end part ?
> We are looking for the Extcore extension for the backend part, are you compatible with it ?
> Also we will migrate to asp core 3.0 once it will be in release. Do you have plans for supporting it ?
> 
> Thanks in advance,
> Alexandre MOULAY

Hello,

sorry, but this repo is just for an idea demo and not ready for production and has not to plan to support
but you can extend this idea for a production-ready plugin system
There is more production ready solution and I recommend you to [read this article](https://blog.angularindepth.com/building-extensible-dynamic-pluggable-enterprise-application-with-angular-aed8979faba5)

**Comment by Razgort** [comment]
Thanks man for the answer, I will post my question there then.
